server {

    listen 8081;

    server_name localhost;

    root /usr/share/nginx/html;

    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /index.html;

    access_log /var/log/nginx/access.log;

    error_log /var/log/nginx/error.log;
}

